#!/bin/bash

PLG_DIR="/boot/optional/plugins/mos-nethogs"

install() {
  # Run installer on first install
  if [[ -x "/usr/bin/plugins/mos-nethogs-install" ]]; then
    /usr/bin/plugins/mos-nethogs-install || true
  fi
}

plugin_update() {
  # Run installer on plugin updates
  if [[ -x "/usr/bin/plugins/mos-nethogs-install" ]]; then
    /usr/bin/plugins/mos-nethogs-install || true
  fi
}

mos_start() {
  # Run installer on system start
  if [[ -x "/usr/bin/plugins/mos-nethogs-install" ]]; then
    /usr/bin/plugins/mos-nethogs-install || true
  fi
}

mos_osupdate() {
  # Run installer on OS updates
  if [[ -x "/usr/bin/plugins/mos-nethogs-install" ]]; then
    /usr/bin/plugins/mos-nethogs-install || true
  fi
}

uninstall() {
  # Cleanup on uninstall
  true
}